# Generated by Django 5.1.3 on 2024-11-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafffiledetail',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='stafffiledetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='UploadedPDF',
        ),
        migrations.DeleteModel(
            name='StaffFileDetail',
        ),
    ]
