# Generated by Django 4.2.16 on 2024-11-29 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_pdf_stafffiledetail_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 29, 17, 54, 50, 517015, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
