# Generated by Django 4.2.16 on 2024-11-29 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_uploadedpdf_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='created_at',
            new_name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='month',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='year',
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='payslip_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 29, 22, 15, 27, 968349, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
