# Generated by Django 4.2.16 on 2024-12-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_stafffiledetail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file',
            field=models.FileField(upload_to='uploads/pdfs'),
        ),
        migrations.AddConstraint(
            model_name='uploadedpdf',
            constraint=models.UniqueConstraint(fields=('file', 'payslip_date'), name='unique_file_date'),
        ),
    ]
